
spring.application.name=tutoria-universitaria
server.port=8081
spring.profiles.active=development
server.servlet.context-path=/vm2

spring.datasource.primary.jdbc-url=jdbc:mysql://localhost:3306/sga_tutorias?useSSL=false&serverTimezone=America/Mexico_City&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
spring.datasource.primary.username=admin_tutorias
spring.datasource.primary.password=icomp2025*
spring.datasource.primary.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.primary.hikari.maximum-pool-size=20
spring.datasource.primary.hikari.minimum-idle=5
spring.datasource.primary.hikari.connection-timeout=30000
spring.datasource.primary.hikari.idle-timeout=600000
spring.datasource.primary.hikari.max-lifetime=1800000

spring.datasource.academico.jdbc-url=jdbc:mysql://localhost:3306/escolares?useSSL=false&serverTimezone=America/Mexico_City&allowPublicKeyRetrieval=true&rewriteBatchedStatements=true
spring.datasource.academico.username=tutorias_ro
spring.datasource.academico.password=TutoriasUnpa2026!
spring.datasource.academico.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.academico.read-only=true

spring.datasource.academico.hikari.maximum-pool-size=5
spring.datasource.academico.hikari.minimum-idle=1
spring.datasource.academico.hikari.connection-timeout=30000
spring.datasource.academico.hikari.initialization-fail-timeout=-1


spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.batch_size=100
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true
spring.jpa.properties.hibernate.batch_versioned_data=true
spring.jpa.properties.hibernate.jdbc.fetch_size=100
spring.jpa.open-in-view=false

spring.flyway.enabled=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=carlosrcardoza634@gmail.com
spring.mail.password=lyppxefcjcqexjus
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.protocol=smtp
spring.mail.default-encoding=UTF-8
spring.mail.properties.mail.debug=false

sincronizacion.espejo.enabled=true
sincronizacion.espejo.cron=0 0 23 * * SUN

cors.allowed-origins=http://localhost:4200,http://tutorias.unpa.edu.mx,https://calificaciones.unpa.edu.mx


logging.level.root=INFO
logging.level.mx.unpa.tutoria=DEBUG
logging.level.org.hibernate.SQL=INFO
logging.level.com.zaxxer.hikari=WARN